// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet.Models;

#nullable disable

namespace Projet.Migrations
{
    [DbContext(typeof(ProjetContext))]
    [Migration("20251124165429_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projet.Models.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Competen__3214EC077FB5CF27");

                    b.HasIndex(new[] { "Nom" }, "UQ__Competen__C7D1C61E70A7CAB6")
                        .IsUnique();

                    b.ToTable("Competence", (string)null);
                });

            modelBuilder.Entity("Projet.Models.CompetenceAcquise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int");

                    b.Property<int?>("Niveau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("PersonneId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Competen__3214EC076EFB2F5B");

                    b.HasIndex("CompetenceId");

                    b.HasIndex("PersonneId");

                    b.ToTable("CompetenceAcquise", (string)null);
                });

            modelBuilder.Entity("Projet.Models.CompetenceSouhaitee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int");

                    b.Property<int?>("NiveauRequis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("OffreId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Competen__3214EC07CE71D8DB");

                    b.HasIndex("CompetenceId");

                    b.HasIndex("OffreId");

                    b.ToTable("CompetenceSouhaitee", (string)null);
                });

            modelBuilder.Entity("Projet.Models.Offre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePostalCible")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosteId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VilleCible")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Offre__3214EC07C6FDC028");

                    b.HasIndex("PosteId");

                    b.ToTable("Offre", (string)null);
                });

            modelBuilder.Entity("Projet.Models.ParametreScoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("ExclureSiExperienceManquante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ExclureSiVilleDiff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OffreId")
                        .HasColumnType("int");

                    b.Property<int?>("PoidsCompetences")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<int?>("PoidsExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<int?>("PoidsLocalisation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.HasKey("Id")
                        .HasName("PK__Parametr__3214EC0790BD927F");

                    b.HasIndex(new[] { "OffreId" }, "UQ__Parametr__540A13133B54325B")
                        .IsUnique();

                    b.ToTable("ParametreScoring", (string)null);
                });

            modelBuilder.Entity("Projet.Models.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnneesExperienceTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("CodePostal")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Personne__3214EC07C70B9BFC");

                    b.HasIndex(new[] { "Email" }, "UQ__Personne__A9D10534B1605CA4")
                        .IsUnique();

                    b.ToTable("Personne", (string)null);
                });

            modelBuilder.Entity("Projet.Models.Poste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Poste__3214EC07DF0C6F2E");

                    b.ToTable("Poste", (string)null);
                });

            modelBuilder.Entity("Projet.Models.CompetenceAcquise", b =>
                {
                    b.HasOne("Projet.Models.Competence", "Competence")
                        .WithMany("CompetenceAcquises")
                        .HasForeignKey("CompetenceId")
                        .IsRequired()
                        .HasConstraintName("FK__Competenc__Compe__5DCAEF64");

                    b.HasOne("Projet.Models.Personne", "Personne")
                        .WithMany("CompetenceAcquises")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Competenc__Perso__5CD6CB2B");

                    b.Navigation("Competence");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("Projet.Models.CompetenceSouhaitee", b =>
                {
                    b.HasOne("Projet.Models.Competence", "Competence")
                        .WithMany("CompetenceSouhaitees")
                        .HasForeignKey("CompetenceId")
                        .IsRequired()
                        .HasConstraintName("FK__Competenc__Compe__59063A47");

                    b.HasOne("Projet.Models.Offre", "Offre")
                        .WithMany("CompetenceSouhaitees")
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Competenc__Offre__5812160E");

                    b.Navigation("Competence");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("Projet.Models.Offre", b =>
                {
                    b.HasOne("Projet.Models.Poste", "Poste")
                        .WithMany("Offres")
                        .HasForeignKey("PosteId")
                        .IsRequired()
                        .HasConstraintName("FK__Offre__PosteId__5070F446");

                    b.Navigation("Poste");
                });

            modelBuilder.Entity("Projet.Models.ParametreScoring", b =>
                {
                    b.HasOne("Projet.Models.Offre", "Offre")
                        .WithOne("ParametreScoring")
                        .HasForeignKey("Projet.Models.ParametreScoring", "OffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Parametre__Offre__66603565");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("Projet.Models.Competence", b =>
                {
                    b.Navigation("CompetenceAcquises");

                    b.Navigation("CompetenceSouhaitees");
                });

            modelBuilder.Entity("Projet.Models.Offre", b =>
                {
                    b.Navigation("CompetenceSouhaitees");

                    b.Navigation("ParametreScoring");
                });

            modelBuilder.Entity("Projet.Models.Personne", b =>
                {
                    b.Navigation("CompetenceAcquises");
                });

            modelBuilder.Entity("Projet.Models.Poste", b =>
                {
                    b.Navigation("Offres");
                });
#pragma warning restore 612, 618
        }
    }
}
